apiVersion: v1
kind: Service
metadata:
  name: tidb
  namespace: db
spec:
  selector:
    pingcap.com/managed-by: tidb-operator
    pingcap.com/cluster: basic
    pingcap.com/component: tidb
  ports:
    - name: mysql
      protocol: TCP
      port: 4000
      targetPort: mysql-client
      