apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: agama
spec:
  replicas: 1 # 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rusxl/agama-frontend:e924a166deed02b71fca3cdbd5cebbab34add1b5
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: API_URL
              value: "http://api.project-x"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
