apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tidb-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/rusXL/project-x.git
    targetRevision: dev
    path: kubernetes/apps/tidb
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
