apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: agama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rusxl/agama-frontend:88a91246a5492723b20eff9a0352139b58239b2d
          ports:
            - name: http
              containerPort: 3000
          env:
            # TODO: Secret/ConfigMap later
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: API_URL
              value: "http://localhost:8000"
          # TODO: resources, probes
