apiVersion: core.pingcap.com/v1alpha1
kind: PDGroup
metadata:
  name: pd
  namespace: db
spec:
  cluster:
    name: basic
  replicas: 1 # 3
  template:
    metadata:
      annotations:
        author: pingcap
    spec:
      version: v8.5.2
      volumes:
      - name: data
        mounts:
        - type: data
        storage: 1Gi
      overlay:
        volumeClaims:
        - name: data
          volumeClaim:
            spec:
              storageClassName: gp2
              