apiVersion: core.pingcap.com/v1alpha1
kind: TiDBGroup
metadata:
  name: tidb
  namespace: db
spec:
  cluster:
    name: basic
  replicas: 2
  template:
    metadata:
      annotations:
        author: pingcap
    spec:
      version: v8.5.2
      overlay:
        pod:
          spec:
            containers:
            - name: tidb
              resources:
                requests:
                  cpu: "250m"
                  memory: "256Mi"
                limits:
                  cpu: "750m"
                  memory: "768Mi"
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        pingcap.com/component: tidb
                    topologyKey: kubernetes.io/hostname
