apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: agama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rusxl/agama-api:d542bbcbaf209aa321e1c7c9ed76f6d0771cdaa1
          ports:
            - name: http
              containerPort: 8000
          env:
            # TODO: Secret/ConfigMap later
            - name: DATABASE_URL
              value: "mysql+aiomysql://root:@tidb.db.svc.cluster.local:4000/agama"
            - name: ALLOWED_ORIGINS
              value: '["*"]'
            - name: APP_NAME
              value: "AGAMA"
          # TODO: resources, probes
