apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rusxl/agama-api:fbb0800ed166d8a7b7192f629a070805cfd30f47
          ports:
            - containerPort: 8000
          env:
            # TODO: Secret/ConfigMap later
            - name: DATABASE_URL
              value: "mysql+aiomysql://root:@tidb.db.svc.cluster.local:4000/agama"
            - name: ALLOWED_ORIGINS
              value: '["*"]'
            - name: APP_NAME
              value: "AGAMA"
          # TODO: resources, probes
