apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: eks
  namespace: fleet-default
spec:
  repo: https://github.com/rusXL/project-x.git
  branch: main
  paths:
    # - kubernetes/eks/mysql
    - kubernetes/eks/tidb-cluster
    - kubernetes/eks/api
    - kubernetes/eks/monitoring
  targets:
    - name: cluster-a
      clusterName: cluster-a
